#pragma once

#include <Windows.h>

namespace winrooted::detail {

static constexpr ULONGLONG O_RDONLY = 0x00000;
static constexpr ULONGLONG O_WRONLY = 0x00001;
static constexpr ULONGLONG O_RDWR = 0x00002;
static constexpr ULONGLONG O_CREAT = 0x00040;
static constexpr ULONGLONG O_CREATE = O_CREAT;
static constexpr ULONGLONG O_EXCL = 0x00080;
static constexpr ULONGLONG O_NOCTTY = 0x00100;
static constexpr ULONGLONG O_TRUNC = 0x00200;
static constexpr ULONGLONG O_NONBLOCK = 0x00800;
static constexpr ULONGLONG O_APPEND = 0x00400;
static constexpr ULONGLONG O_SYNC = 0x01000;
static constexpr ULONGLONG O_ASYNC = 0x02000;
static constexpr ULONGLONG O_CLOEXEC = 0x80000;
static constexpr ULONGLONG O_DIRECTORY = 0x04000;        // target must be a directory
static constexpr ULONGLONG O_NOFOLLOW_ANY = 0x200000000; // disallow symlinks anywhere in the path
static constexpr ULONGLONG O_WRITE_ATTRS = 0x800000000;  // FILE_WRITE_ATTRIBUTES, used by Chmod

static constexpr ULONGLONG O_FILE_FLAG_OPEN_NO_RECALL = FILE_FLAG_OPEN_NO_RECALL;
static constexpr ULONGLONG O_FILE_FLAG_OPEN_REPARSE_POINT = FILE_FLAG_OPEN_REPARSE_POINT;
static constexpr ULONGLONG O_FILE_FLAG_SESSION_AWARE = FILE_FLAG_SESSION_AWARE;
static constexpr ULONGLONG O_FILE_FLAG_POSIX_SEMANTICS = FILE_FLAG_POSIX_SEMANTICS;
static constexpr ULONGLONG O_FILE_FLAG_BACKUP_SEMANTICS = FILE_FLAG_BACKUP_SEMANTICS;
static constexpr ULONGLONG O_FILE_FLAG_DELETE_ON_CLOSE = FILE_FLAG_DELETE_ON_CLOSE;
static constexpr ULONGLONG O_FILE_FLAG_SEQUENTIAL_SCAN = FILE_FLAG_SEQUENTIAL_SCAN;
static constexpr ULONGLONG O_FILE_FLAG_RANDOM_ACCESS = FILE_FLAG_RANDOM_ACCESS;
static constexpr ULONGLONG O_FILE_FLAG_NO_BUFFERING = FILE_FLAG_NO_BUFFERING;
static constexpr ULONGLONG O_FILE_FLAG_OVERLAPPED = FILE_FLAG_OVERLAPPED;
static constexpr ULONGLONG O_FILE_FLAG_WRITE_THROUGH = FILE_FLAG_WRITE_THROUGH;

static constexpr ULONG FileFlagsMask = 0xFFF00000;

static constexpr ULONGLONG ValidFileFlagsMask = O_FILE_FLAG_OPEN_REPARSE_POINT | O_FILE_FLAG_BACKUP_SEMANTICS |
    O_FILE_FLAG_OVERLAPPED | O_FILE_FLAG_OPEN_NO_RECALL | O_FILE_FLAG_SESSION_AWARE | O_FILE_FLAG_POSIX_SEMANTICS |
    O_FILE_FLAG_DELETE_ON_CLOSE | O_FILE_FLAG_SEQUENTIAL_SCAN | O_FILE_FLAG_NO_BUFFERING | O_FILE_FLAG_RANDOM_ACCESS |
    O_FILE_FLAG_WRITE_THROUGH;

} // namespace winrooted::detail
